# Example: Basic CodeThreat Security Scan
# Add this to .github/workflows/security.yml in your repository

name: Security Scan
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  security:
    name: CodeThreat Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write  # Required for SARIF upload
      contents: read
      actions: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: CodeThreat Security Scan
        uses: CodeThreat/codethreat-appsec-github-action@master
        with:
          # Required
          api-key: ${{ secrets.CODETHREAT_API_KEY }}
          server-url: ${{ secrets.CODETHREAT_SERVER_URL }}  # e.g., 'https://api.codethreat.com'
          organization-slug: ${{ secrets.CODETHREAT_ORG_SLUG }}  # Your organization slug
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Required for SARIF upload
          
          # GitHub Security tab integration
          upload-sarif: true
          output-format: 'sarif'
